import type { NextPage } from 'next';
import { signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const { data, status } = useSession();
  const router = useRouter();

  const handleSignOut = () => {
    signOut();
  };
  useEffect(() => {
    if (status !== 'authenticated') {
      router.push('/login');
    }
  }, [data, status, router]);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="App-header">
        <nav className="nav"></nav>
      </header>
      <main>
        <h1>Homepage</h1>
        <button onClick={handleSignOut}>Sign out</button>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
