import type { NextPage } from 'next';
import { signIn } from 'next-auth/react';
import Head from 'next/head';

const Login: NextPage = () => {
  const handleFacebookSignIn = async () => {
    await signIn('facebook');
  };
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="App-header">
        <nav className="nav"></nav>
        <button onClick={handleFacebookSignIn}>Sign in With Faceebok</button>
      </header>
      <main>
        <h1>Login</h1>
      </main>
      <footer></footer>
    </div>
  );
};

export default Login;
