import type { NextPage } from 'next';
import { signIn, useSession } from 'next-auth/react';
import Head from 'next/head';

const Login: NextPage = () => {
  const { data, status } = useSession();
  const handleInstagramSignIn = async () => {
    await signIn('instagram');
  };
  const handleGoogleSignIn = async () => {
    await signIn('google');
  };
  console.log(data, status);
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="App-header">
        <nav className="nav"></nav>
        <button onClick={handleInstagramSignIn}>Sign in With Instagram</button>
        <button onClick={handleGoogleSignIn}>Sign in With Google</button>
      </header>
      <main>
        <h1>Login</h1>
      </main>
      <footer></footer>
    </div>
  );
};

export default Login;
