import type { NextPage } from 'next';
import Head from 'next/head';
import Input from 'components/atoms/Input/Input';
import Button from 'components/atoms/Button/Button';
import { useForm } from 'react-hook-form';
import axios from 'axios';

interface RegisterFormData {
  name: string;
  login: string;
  password: string;
  repeatPassword: string;
}

const Register: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const onSubmit = async (data: RegisterFormData): void => {
    const response = await axios.post('/api/register', data);
    console.log(response);
  };

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="App-header">
        <nav className="nav"></nav>
      </header>
      <main>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Input type="text" alt="name" placeholder="Podaj imię" label="name" {...register('name')} />
          <Input type="text" alt="surname" placeholder="Podaj nazwisko" label="surname" {...register('name')} />
          <Input type="email" alt="login" placeholder="Podaj login" label="login" {...register('login')} />
          <Input type="password" alt="password" placeholder="Podaj hasło" label="password" {...register('password')} />
          <Input type="password" alt="repeatPassword" placeholder="Powtórz hasło" label="Powtórz hasło" {...register('repeatPassword')} />
          <Button type="submit">Zarejestruj się!</Button>
        </form>
      </main>
      <footer></footer>
    </div>
  );
};

export default Register;
